name: FoodSteal
version: '${project.version}'
main: dev.JackaBoi.FoodSteal.Main
api-version: 1.18
authors: [ JackaBoi ]
description: Food Steal Plugin
website: https://www.jackaboi.net/plugins

commands:
  setmaxfoodlevel:
    description: Sets the targeted player's food level.
    usage: /setmaxfoodlevel <player> <food level [0-20]>
