name: FoodSteal
version: a01
main: dev.JackaBoi.FoodSteal.Main
api-version: 1.18
authors: [ JackaBoi ]
description: Food Steal Plugin
website: https://www.jackaboi.net/plugins

commands:
  setmaxfoodlevel:
    description: Sets The Max Food Level of Target
    usage: /setmaxfoodlevel <player> <foodlevel [0-20]>